#%RAML 1.0 Trait
    queryParameters:
      startPage:
        description: Starting page number, first page is 1
        type: integer
        example: 1
      pageSize:
        description: Maximum number of entries per page
        type: integer
        example: 10